# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

########### INSTANCE-SPECIFIC SETTINGS ###########

# ------------ General Settings ------------ #

# Title of this response effort (used in header and displayed on most pages)
title: CfA Hurricane Response

# Email address to use for sending messages
email: email@hurricane-response.org

# Description of this response effort (only used in header meta tags, not displayed)
description: >- #m this means to ignore newlines until "baseurl:"
  Code for America 2019 Response

# Subpath of your site, e.g. /blog (used for constructing relative/internal links)
baseurl: ""

# URL to the volunteer sign-up page
help_url: "https://www.codeforamerica.org"

# For Text Bot Settings: _data/txtbot.yml
# For Map Settings:      _data/map.yml


########### COMMON SETTINGS ###########

defaults:
  -
    values:
      layout: default

permalink: pretty

# Base hostname & protocol for your site, e.g. http://example.com (not currently used)
url: ""

# Site logo (not currently used)
logo: "https://avatars0.githubusercontent.com/u/43193416?s=400&u=8e1d97c94fa7a9611c8b8fa765e68c8fe86e2e7c"

gtag: UA-125718262-3

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

